### ISSUE TITLE
[Bug Bounty] Send Amount > Back Arrow > Back button should exit app

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#106]
This current flow returns to the send screen when it should exit instead.

**Comment by CrystalPony** [comment]
This issue is caused by the back arrow in some instances utilizing onClickNavTo with a normal destination, which causes the current view to be pushed to the stack. A simple fix would be to replace onClickNavTo with onClickNavBack or to replace the destination behavior with a Pop To behavior, however that breaks the sliding exit animation.
The Pop Exit animation value is supposed to be used but it's not working and I don't know why.

**Comment by gmale** [comment]
Your suggestion was exactly correct. Thanks!

As far as I'm concerned, you fixed this bug, as well and that should be included for bounties.

**Comment by CrystalPony** [comment]
I wouldn't mind that 😄
