### ISSUE TITLE
Possible shell injection in writeLogcat()

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-android-wallet#121]
In the following code, if `ZcashWalletApp.instance.filesDir` could be controlled by an attacker, they might be able to inject arbitrary shell commands:

```
    private fun writeLogcat(): File? {
        try {
            val outputFile = File("${ZcashWalletApp.instance.filesDir}/logs", "developer_log.txt")
            val cmd = arrayOf("/bin/sh", "-c", "logcat -v time -d | grep \"@TWIG\" > ${outputFile.absolutePath}")
            Runtime.getRuntime().exec(cmd)
```

I'm pretty sure `ZcashWalletApp.instance.filesDir` comes from the OS and can be trusted so this is a non-issue. @gmale if that's the case you can remove the security-mvp label without fixing this.

An easy fix would be to ensure `File(outputFile.absolutePath).isFile()` returns true before running the command. Then the worst that could happen is some other file named `developer_log.txt` gets overwritten.

You should also have quotes around the path, like this, in case there are spaces in it:

```
val cmd = arrayOf("/bin/sh", "-c", "logcat -v time -d | grep \"@TWIG\" > \"${outputFile.absolutePath}\"")
```

**Comment by gmale** [comment]
This might explain why the developer logs don't work on some people's devices. Perhaps "the directory on the filesystem where files created with `openFileOutput` are stored" happens to contain spaces. I didn't think that was possible but maybe it happens when people put their apps on SD cards?

Either way,  this seems worthwhile to improve. Eventually, we might want to investigate a saver way to extract logs and we should probably only enable this feature in internal builds.

This is another good case for making completely separate builds for internal use that can exclude stuff like this.

**Comment by gmale** [comment]
Note: this problem has been improved but not 100% fixed so we are leaving it open.

**Comment by gmale** [comment]
Addressed in https://github.com/zcash/zcash-android-wallet/commit/1f52ce7324c058f11d75c5d45bce251d0ba57caa.

Logs were not working on certain phones because the `/bin/sh` command was not available. To fix that, I switched to writing logs directly to the developer log file rather than scrapping them into that file on demand.
