### ISSUE TITLE
Failed to encode transaction for every wallet created after 1 millionth block

### ISSUE THREAD

**Issue by nighthawk24** [zcash/zcash-android-wallet#208]
Newly created wallets are failing send a transactions, every send tx errors out with message "Failed to encode transaction."
Expected: I expect that a newly created wallet to be able to send transactions.

 - Android Device: Essential PH-1
 - Android Version 11

1. Create a New Wallet
2. Receive ZEC
3. Send ZEC
4. See error: "Failed to encode transaction."

**Comment by nighthawk24** [comment]
Closing as this was an environment related issue with the local network blocking connections to download.z.cash that was called during the send transaction flow.

**Comment by gmale** [comment]
Could not reproduce with the latest version of the wallet `1.1.0-alpha37` 

@nighthawk24 which version are you seeing this on?

**Comment by gmale** [comment]
My internet has been spotty, ignore my previous comment, didn't see that this was closed!

Thanks for spotting this and testing it and finding the root issue!

I am a bit concerned though that there was an encoding issue because that shouldn't involve the network at all, given that the transaction is encoded on the device. Keep an eye on it and if you see anything weird, let me know!
