### ISSUE TITLE
Build autoshielding information screen

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet#269]
As a user, I'd like to have a message explaining auto-shielding so that I'm aware that this new feature exists in my wallet.

### Implementation details
This issue is for implementing this screen as a fragment, similar to the [ProfileFragment](https://github.com/zcash/zcash-android-wallet/blob/master/app/src/main/res/layout/fragment_profile.xml). Other issues will cover wiring the screen into the app.

#### In-Scope
- building the screen
- wiring the screen into navigation
- making the screen show when the app launches
- ensuring that the screen only shows once

**Comment by gmale** [comment]
Here is a quick screenshot of the screen. At this time, I'm not able to get the sketch file but hopefully you still have access to one you've used previously.

<img width="460" alt="Screen Shot 2021-06-12 at 9 23 10 AM" src="https://user-images.githubusercontent.com/1699841/121777568-d6719900-cb60-11eb-9107-c5a9135579f7.png">

Note: The blue lines are not part of the design. Imagine they are not there.

**Comment by gmale** [comment]
@herou Updated link to designs:
https://xd.adobe.com/view/e2553227-e67c-4671-9988-596a53eab10e-b706/

**Comment by pacu** [comment]
@herou do you have any updates on this issue?

**Comment by ccjernigan** [comment]
@pacu How closely do we typically try to match designs?  Do we have wiggle room to make minor adaptations, especially in light of implementation details?

The text is grey, with a few words turned white for contrast.  While we can do this on Android, it requires going outside of the resource system and implementing spans at runtime which are sort of complex because we have to parse the string, find the start and end points for each span, set the color for those indexes, etc.  Trying to make this work correctly with localization is also a pain.  I think it's similar to crafting an `NSAttributedString`.

A much simpler implementation would be to use bold or italics for the words we want to stand out.  That can be implemented using simple HTML tags in our strings.xml file.  This is faster to implement, easier to test, and simpler to manage with localization too.

What are your thoughts?

**Comment by pacu** [comment]
It does not need to be pixel perfect. Yes, localization is indeed a problem but this screen does not have translations, so don't worry too much about it. if HTML tags serves our purposes enough so that the text distribution matches to the design. I think we call it done. thoughts @geffenz ?

**Comment by ccjernigan** [comment]
This is roughly what it looks like with bold instead of using color.  (Please ignore the guide lines from the Android layout editor).

<img width="525" alt="image" src="https://user-images.githubusercontent.com/699907/132753583-3a1f773d-3457-4c3a-8133-0e511ecf575a.png">

**Comment by ccjernigan** [comment]
Also what shade of grey is this using?  The hex value of the design appears to be `bbbbbb`.  I'm guessing we'd like to stick with a value already defined.  Perhaps that hex value maps to one of these, once the transparency is factored in?

```
    <color name="zcashWhite">#F5F5F5</color>
    <color name="zcashGray">#616161</color>
    <color name="zcashWhite_12">#1FFFFFFF</color>
    <color name="zcashWhite_24">#3DFFFFFF</color>
    <color name="zcashWhite_40">#66FFFFFF</color>
    <color name="zcashWhite_50">#80FFFFFF</color>
    <color name="zcashWhite_60">#A3FFFFFF</color>
    <color name="zcashWhite_87">#BFFFFFFF</color>
    <color name="zcashWhite_light">#EDEDED</color>
    <color name="zcashBlack_light">#2B2B2B</color>
    <color name="zcashBlack_12">#1F000000</color>
    <color name="zcashBlack_40">#66000000</color>
    <color name="zcashBlack_54">#8A000000</color>
    <color name="zcashBlack_87">#DD000000</color>
    <color name="zcashBlack_dark">#171717</color>
```
